### ISSUE TITLE
Reverso Context Broken

### ISSUE THREAD

**Issue by BlackberrieCake137** [you-apps/TranslateYou#315]
### Steps to reproduce

Translate with Reverso

### Expected behavior

Contexts appear on Reverso's page with the 'translated from' language  followed by the translation in said context

### Actual behavior

Yet, instead, when using Translate You all of the 'translated from' entries are listed at the top with the translations all listed at the bottom, which breaks the linking between contexts and negates much of the purpose for using reverso

### Translate You version

6.3

### Android version

Android 13

### Other details

![Screenshot_20230815-220404](https://github.com/you-apps/TranslateYou/assets/121859020/63b8f5e0-d9d2-4ab3-8f61-789395988ef8)
![Screenshot_20230815-220351](https://github.com/you-apps/TranslateYou/assets/121859020/951136b2-d8df-474d-acc8-962334a75150)
![Screenshot_20230815-220317](https://github.com/you-apps/TranslateYou/assets/121859020/7e2adbd5-c2ed-4add-a278-9093c8a21243)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's not how Translate You works. The Reverso API returns a `translatedText` param that contains the main translation according to Reverso - anything else is supplementary.
Changing that would require rewriting the UI of Translate You for one single engine, although 9 are supported in general, and Reverso is not the main engine.
