### ISSUE TITLE
no xml file found

### ISSUE THREAD

**Issue by muhammadZubairferozi** [you-apps/TranslateYou#316]
### Describe your suggested feature

brother there is no xml file can you tell me from where we can find it and how can we modify it

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
What are you talking about?
