### ISSUE TITLE
Support voice translation

### ISSUE THREAD

**Issue by K4LCIFER** [you-apps/TranslateYou#321]
### Describe your suggested feature

You speak into the microphone, the app parses the voice into text, and then it translates it.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Supported when Google services are available

**Comment by K4LCIFER** [comment]
> Supported when Google services are available

Do you mean that I need to enable a setting? Or do you mean that this is planned in the future?
