### ISSUE TITLE
floating button and OCR image translation

### ISSUE THREAD

**Issue by Pantyhose-X** [you-apps/TranslateYou#332]
## floating button
It works as a gesture app, allowing you get texts quickly
https://github-production-user-asset-6210df.s3.amazonaws.com/42504385/267070107-8b0813c8-8627-41ee-bb20-b169adba92d6.gif

![1](https://github-production-user-asset-6210df.s3.amazonaws.com/42504385/267070107-8b0813c8-8627-41ee-bb20-b169adba92d6.gif)

## OCR image translation
https://github-production-user-asset-6210df.s3.amazonaws.com/42504385/267070210-7e4874bc-2e80-48a4-9e68-0dc92b27f137.gif

![Gif_20230911095909](https://github-production-user-asset-6210df.s3.amazonaws.com/42504385/267070210-7e4874bc-2e80-48a4-9e68-0dc92b27f137.gif)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's not planned currently.

**Comment by Zig-Rust-Odin** [comment]
floating button: Crop an image such as in games to screenshot , OCR Get the text

@Pantyhose-X Demonstration from non -free fooview app
https://play.google.com/store/apps/details?id=com.fooview.android.fooview

These two features are very useful for people who don't speak English.

**Comment by jujubeja** [comment]
Two very useful features!
You gif from https://play.google.com/store/apps/details?id=com.fooview.android.fooview
