### ISSUE TITLE
Increase Translated portion area

### ISSUE THREAD

**Issue by Drangonfly30** [you-apps/TranslateYou#333]
### Describe your suggested feature

Hello, the area in which translation is shown is really small and we have to swipe up and down multiple times to get complete information, 
![translate you ss](https://github.com/you-apps/TranslateYou/assets/113085944/55b12549-03e4-4636-ae32-57fd97efdf5c)

I think the area can be increased or maybe it can be done like google translate

![WhatsApp Image 2023-09-15 at 01 19 21](https://github.com/you-apps/TranslateYou/assets/113085944/355064fa-3396-4eea-a76c-835c0f883692)

here you can swipe and get the complete information on one page, which uses the space more efficiently.

It's really just a suggestion and even without this, the app works totally fine and great.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I think the current layout works well enough, we don't need to reinvent the wheel and copy everything other apps do.
