### ISSUE TITLE
Adding Apertium beta languages

### ISSUE THREAD

**Issue by Prasanta-Hembram** [you-apps/TranslateYou#336]
### Describe your suggested feature

Their are many languages in[ Apertium beta](https://beta.apertium.org/index.eng.html#?dir=eng-sat&q=One%20hundred%20and%20seventy) which are giving best results. Adding them will increase the number of languages supported in Apertium.

### Other details

- An option for changing the url can be given.(Instance)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Feel free to open a PR for that.
