### ISSUE TITLE
API integration: Mozhi

### ISSUE THREAD

**Issue by Terkyz** [you-apps/TranslateYou#343]
### General informations

[Mozhi](https://codeberg.org/aryak/mozhi) as their Codeberg page explains "It was initially made as a maintained fork/rewrite of [simplytranslate](https://codeberg.org/SimpleWeb/SimplyTranslate-Web), but has grown to have a lot more features as well!"

What personally attracted my attention about this front-end is that it supports DeepL without using an API Key, I know that many front-ends already support this and that due to usage the API is blocked, but having more options is always good.

### API basic informations

- [ ] This translation engine requires a registered account.
- [ ] This translation engine requires an free api key.
- [ ] This translation engine requires an paid api key.

### Translation engine service endpoints

https://mozhi.aryak.me/api/swagger/index.html#/default/get_api_source_languages

### Details and links

I am not sure about the API Basic Informations checks, please edit my post in case the information is wrong.

### Acknowledgements

- [X] I have searched the existing requests and this is a new ticket, **NOT** a duplicate or related to another open or closed request.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
It seems like the API routes are still the same as of SimplyTranslate, could you please try to use a Mozhi instance via the SimplyTranslate engine?

If that works, we can just add the additional engines Mozhi supports to the already existing SimplyTranslate implementation.
