### ISSUE TITLE
Can't download language data

### ISSUE THREAD

**Issue by julianfairfax** [you-apps/TranslateYou#352]
### Steps to reproduce

1. Open the app
2. Go to the settings
3. Click on the image translation language data button
4. Try to download a language

### Expected behavior

It should download the language data for that language.

### Actual behavior

The download button next to the language spins for a bit, but nothing is downloaded.

### Translate You version

7.1

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Can't reproduce on my end, and since there's no debug log or screen recording, there's nothing to investigate here.

**Comment by julianfairfax** [comment]
Screen recording requested: https://github.com/you-apps/TranslateYou/assets/43753131/2a117057-8e29-4c2d-96e8-7000abb693ca

**Comment by zdat** [comment]
Same for me. Any ideas?

@julianfairfax did you ever find a fix?
