### ISSUE TITLE
Google Translator API implement

### ISSUE THREAD

**Issue by EHMilon** [you-apps/TranslateYou#361]
### Describe your suggested feature

Google Translator offer a lot of languages. It not only offer translation, it also offers dictionary features with free off cost. If you translate one single word in gTranslator it will provide all the similar translated word. Please add google Translator API.
![Screenshot_20231028-141456](https://github.com/you-apps/TranslateYou/assets/107425940/8614075e-2d38-4160-9119-98e1fc27b8e7)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Lingva, Mozhi and SimplyTranslate have support for the Google Translator.

**Comment by EHMilon** [comment]
> Lingva, Mozhi and SimplyTranslate have support for the Google Translator.

I think google translator implementation will be the better choice. Lingva offer only one word suggestion. SimplyTranslator is not working.
