### ISSUE TITLE
Pop up display

### ISSUE THREAD

**Issue by EHMilon** [you-apps/TranslateYou#362]
### Describe your suggested feature

Suppose I am reading .pdf or .epub file on my android device. I discover an unknown word. To know the translation of this word, we need to select this word and share it or copy and paste the word to another translator app such as Google Translator. But It's really take time, and we lose our focus to read. In browser there are a lot of extension available to select and translate. I resource a lot, but I don't find any app for android. I give you a .gif format image. Is it possible to do it like this.
### Suppose I select a word and click on this selected word, it will translate the word.

![Recording 2023-10-28 151428](https://github.com/you-apps/TranslateYou/assets/107425940/5cfc6507-8396-4374-a3e0-4b49bfde15cd)

### Otherwise, selecting a word small icon will be open and click to the icon will show translation.

![translate2](https://github.com/you-apps/TranslateYou/assets/107425940/7fcae9c8-df44-42ff-bf45-1f195000c920)

### This feature will make this app different from other apps. Please make this thing consider. It will help us a lot. 
@Bnyro 

### Other details

In this example, I use xTranslator Chrome extension. This extension also an open source project. You can easily find this in github repository. Here is the link, https://github.com/ixrock/XTranslate

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's not possible on a technical level via Android.
