### ISSUE TITLE
Default LibreTranslate instance doesn't work

### ISSUE THREAD

**Issue by pikatchu2k3** [you-apps/TranslateYou#373]
### Steps to reproduce

1. Install app
2. Enter a sentence in French, English or German
3. Getting " error communicating with server"
4. Changing target language does not show any language to select 
5. Changing translate engines gives the same error 
6. Downloading picture recognition tesseract modules works fine. (That means: Internet access is working)

### Expected behavior

App should translate

### Actual behavior

Error message as above 

Tried solutions:
I disabled also any DNS server.
I switched from Wi-Fi to LTE

### Translate You version

8.0 from fdroid

### Android version

14

### Other details

Pixel 7 pro
Graphene OS
Network permissions allowed

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Set a different engine or instance url in the settings, the default one seems to be dead.

**Comment by basings** [comment]
There are some servers listed here https://github.com/LibreTranslate/LibreTranslate e.g. https://translate.terraprint.co/
