### ISSUE TITLE
Multiline text translation problem

### ISSUE THREAD

**Issue by nvllz** [you-apps/TranslateYou#382]
### Steps to reproduce

Try to translate any multiline input, like:
>Uno
Dos
Cinco

### Expected behavior

I expect the application to handle multiline inputs (text1{ENTER}text2) without requiring manual removal of line breaks.

### Actual behavior

Regardless of the selected translation engine, the app does not currently handle multiline inputs and does not appear to send them for translation.

### Translate You version

8.0

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
This does work perfectly fine for me (tested with Mozhi engine).
