### ISSUE TITLE
Balance icons size

### ISSUE THREAD

**Issue by nvllz** [you-apps/TranslateYou#383]
### Steps to reproduce

Enter any text to translation on the main screen.

### Expected behavior

I think it would look better if all the icons had the same size.

### Actual behavior

Two of the icons are larger than the remaining ones.

![image](https://github.com/you-apps/TranslateYou/assets/110673332/d13c78f4-333c-432b-a681-40156040dc24)

### Translate You version

8.0

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Feel free to create a pull request, otherwise not planned.
