### ISSUE TITLE
"Error with the communication with the server"

### ISSUE THREAD

**Issue by Acelya-9028** [you-apps/TranslateYou#384]
### Steps to reproduce

First launch the app after install.

### Expected behavior

This message doesn't appear and the traduction just works by default.

### Actual behavior

This message appear and the traduction doesn't work which annihilates the usefulness of this app.

### Translate You version

8.0

### Android version

14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
duplicate of #373
