### ISSUE TITLE
Error in communication with server

### ISSUE THREAD

**Issue by EnchantedGoldenApple** [you-apps/TranslateYou#391]
### Steps to reproduce

1. Choose Deepl as translate engine
2. Insert key
3. receive error
![photo_2023-12-23_23-14-18](https://github.com/you-apps/TranslateYou/assets/77505572/dd6a4104-a45a-4382-b06b-8a85ec6dd8cb)
 

### Expected behavior

Translate

### Actual behavior

Error, and no result

### Translate You version

8.0

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by bloodyeyesblackblood** [comment]
#384 & #373

**Comment by Bnyro** [comment]
Clear cache and change instance.
