### ISSUE TITLE
Add keyboard button at the bottom

### ISSUE THREAD

**Issue by iswac** [you-apps/TranslateYou#397]
### Describe your suggested feature

Can you add button like this for easily translating?
![0240131-02082](https://github.com/you-apps/TranslateYou/assets/157625006/92adcdd5-c39c-4fb9-bf80-0e9c17ecd182)

### Other details

On large screen phones and tablets, it can sometimes be difficult to click on the top.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Sorry, that's not planned.
