### ISSUE TITLE
Api support request: DeeplX

### ISSUE THREAD

**Issue by KiriKira** [you-apps/TranslateYou#403]
### Describe your suggested feature

Here is an unofficial DeepL API project https://github.com/OwO-Network/DeepLX which doesn't need token.
I'm not sure it's fully compatible with the official API, but it would be nice to have support for custom URLs to use a self-hosted unofficial API like this one.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
DeepLX isn't compatible sith DeepL, it would need to be a new dedicated engine.

**Comment by Bnyro** [comment]
Closing as there doesn't seem to be much interest in this.

Also, the Mozhi engine supports DeeplX.
