### ISSUE TITLE
Support playing inserted text as audio/voice

### ISSUE THREAD

**Issue by Bnyro** [you-apps/TranslateYou#414]
### Describe your suggested feature

> I am doing a language tandem.
> If I then receive messages in the new language in my Messenger, I can also share with TranslateYou using the share function. I assume that no sensitive information is sent over the Internet to servers that TranslateYou uses, right?
I have set the languages from where to where I want to translate. What irritates me: I can listen to the translation. However, this is then the translation into my own language. It would make more sense to me if the button for audio playback was also available for the language I am currently learning. In other words, the language that I insert as the source text for a translation in TranslateYou.

extracted from an email I got ...

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by sudwhiwdh** [comment]
How complicated is this to implement if the playback of translated text is already possible?

**Comment by Bnyro** [comment]
> How complicated is this to implement if the playback of translated text is already possible?
>
Not very complicated, you can probably do that within 20 lines by just copying the code for the translated text.

**Comment by sudwhiwdh** [comment]
> Not very complicated, you can probably do that within 20 lines by just copying the code for the translated text.

Can you give me a hint where the code is located exactly?

**Comment by sudwhiwdh** [comment]
Thank you very much!

**Comment by sudwhiwdh** [comment]
@Bnyro Could you imagine doing a new release?

**Comment by sudwhiwdh** [comment]
Can you imagine doing a new release?
