### ISSUE TITLE
Request to add english to language typing support for vernacular languages like hindi and kannada.

### ISSUE THREAD

**Issue by vishalscodes** [you-apps/TranslateYou#420]
### Describe your suggested feature

It could work like https://www.easyhindityping.com but in the app itself.

https://github.com/you-apps/TranslateYou/assets/104351431/26169474-5129-4c37-b927-005f57c042b3

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's out of scope for the project.
