### ISSUE TITLE
Change additional information language

### ISSUE THREAD

**Issue by Terkyz** [you-apps/TranslateYou#426]
### Describe your suggested feature

It would be useful some feature to change the "additional information" language.

### Other details

My native language is other than english but I usually use my OS and read everything on english, that includes TranslateYou, when I translate some word to my native language I wish that the definition or additional information were in my language instead of english, so I can better understand its meaning.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
We display all the information returned by the translation engine used - if it's the source or the target language (or both) can vary depending on the translation engine used.
