### ISSUE TITLE
SimplyTranslate network error

### ISSUE THREAD

**Issue by user-naa** [you-apps/TranslateYou#432]
### Steps to reproduce

1. Select SymplyTranslate in settings
2. Try to translate anything

### Expected behavior

Translating should work

### Actual behavior

Appears toast with error "Error in communication with the server".

### Translate You version

9.0

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
You have to select a working instance in the settings, simplytranslate.org is probably no longer working because SimplyTranslate was abandoned.

**Comment by user-naa** [comment]
@Bnyro 
![Screenshot_20240523-170042_Mull](https://github.com/you-apps/TranslateYou/assets/95368060/c53d6538-1f3a-4f5a-bd48-f7fc838ed758)
The site simplytranslate.org works fine from browser, but doesn't work from app
