### ISSUE TITLE
Add DuckDuckGo translations

### ISSUE THREAD

**Issue by SpiritOTHawk** [you-apps/TranslateYou#436]
### General informations

Official information about it:
https://duckduckgo.com/duckduckgo-help-pages/results/translation/

### API basic informations

- [ ] This translation engine requires a registered account.
- [ ] This translation engine requires an free api key.
- [ ] This translation engine requires an paid api key.

### Details and links

Maybe this: https://github.com/deedy5/duckduckgo_search
I found only python lib, sorry.

### Acknowledgements

- [X] I have searched the existing requests and this is a new ticket, **NOT** a duplicate or related to another open or closed request.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Support for DuckDuckGo is not planned due to the fact that it requires HTML scraping for accessing vqd tokens which is
1. susceptible for breaking
2. very slow
