### ISSUE TITLE
Backup/restore app configuration

### ISSUE THREAD

**Issue by gOg1zs4KhIUSoTClcSN-eIxT** [you-apps/TranslateYou#439]
### Describe your suggested feature

Add an option to backup/restore app configuration.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Issue template not used properly.
