### ISSUE TITLE
Tapping sound icon does not generate speech

### ISSUE THREAD

**Issue by popogomo** [you-apps/TranslateYou#442]
### Steps to reproduce

Version: 10.0, downloaded from GitHub
OS: GrapheneOS

**Issue:**

Nothing happens when I tap to sound icon next to original text or translated text. It supposed to speak the word /sentence but nothing happens. This is true for any language (even from English to English).

I am using Ligva as my engine but also tried SimplyTranslate engine.

### Expected behavior

It should properly generate the speech after tapping the sound button

### Actual behavior

Doesn't do anything

### Translate You version

10.0

### Android version

12, GrapheneOS

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by I-I-IT** [comment]
> I am using Ligva as my engine but also tried SimplyTranslate engine.

This is my two cents guess : those engine do not support TTS.

**Comment by jkelly99** [comment]
> > I am using Ligva as my engine but also tried SimplyTranslate engine.
> 
> This is my two cents guess : those engines do not support TTS.

I have the same issue with all the engines. No sound output. Other apps working fine with TTS.

**Comment by drogga** [comment]
...maybe you can try v9.0 or lower to see if some of the changes didn't broke this...

**Comment by I-I-IT** [comment]
> > > I am using Ligva as my engine but also tried SimplyTranslate engine.
> > 
> > 
> > This is my two cents guess : those engines do not support TTS.
> 
> I have the same issue with all the engines. No sound output. Other apps working fine with TTS.

I might be wrong, but Translate You probably will need to use TTS from the translation provider (since translation is in a language likely not on your phone). And as AFAIK only Google provides it and it doesn't work/ it's broken.

**Comment by czarnyckm** [comment]
Speech work's fine with version 9.0. 
With 10.0 does not work anymore.

**Comment by Bnyro** [comment]
Feel free to create a pull request with a fix.
