### ISSUE TITLE
Typo in F-Droid and IzzyOnDroid

### ISSUE THREAD

**Issue by dmlls** [you-apps/TranslateYou#445]
### Describe your suggested feature

There is a small typo in the app description in [F-Droid](https://f-droid.org/packages/com.bnyro.translate/) and [IzzyOnDroid](https://apt.izzysoft.de/fdroid/index/apk/com.bnyro.translate):

> It supports multiple different translation ***engiens*** such as LibreTranslate, Lingva, DeepL and more.

### Other details

_Note:_ This didn't fit into any of the issue templates. It is obviously _not_ a feature request. It might be sensible to allow to open issues without using any of the available templates.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Please feel free to open a pull request, the file you're talking about is https://github.com/you-apps/TranslateYou/blob/master/fastlane/metadata/android/en-US/full_description.txt
