### ISSUE TITLE
Pop up mode

### ISSUE THREAD

**Issue by Solovertical** [you-apps/TranslateYou#450]
### Describe your suggested feature

* When translating in app like twitter, it opens the app instead of on screen. 
* Open pop mode from bottom like unofficial [Foss Deepl](https://github.com/sakusaku3939/DeepLAndroid) app
* Show translated text first instead of original text in pop-up mode
* Removes unwanted space so text can be displayed in a larger area

| ![you](https://github.com/user-attachments/assets/0838df98-d650-4c5d-953d-1fea0b0b62ec)   | ![deepl](https://github.com/user-attachments/assets/e0507475-97a2-47c4-813a-0b77a41990ad)   |
| ---- | ---- |

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Not planned, the interface is aiming to be similar to the normal translation interface.
