### ISSUE TITLE
DeepLx

### ISSUE THREAD

**Issue by fideliochan** [you-apps/TranslateYou#451]
### General informations

It lets you use deepl without api key https://github.com/OwO-Network/DeepLX

### API basic informations

- [ ] This translation engine requires a registered account.
- [ ] This translation engine requires an free api key.
- [ ] This translation engine requires an paid api key.

### Translation engine service endpoints

/translate

### Details and links

https://github.com/OwO-Network/DeepLX

### Acknowledgements

- [X] I have searched the existing requests and this is a new ticket, **NOT** a duplicate or related to another open or closed request.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
We already support deepl without authentication.
