### ISSUE TITLE
Auto Language Detection display detected Lang.

### ISSUE THREAD

**Issue by derei** [you-apps/TranslateYou#452]
### Describe your suggested feature

When translation is set to autodetect language, it would be extremely useful to:
1. display the detected language.
2. allow the user to submit a correction suggestion in case of wrong autodetection.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
> display the detected language.
>
That's already implemented, it's currently not shown due to a bug that will be fixed next release.

> allow the user to submit a correction suggestion in case of wrong autodetection.
>
None of the translation engine APIs supports that.
