### ISSUE TITLE
Custom Language Selection for Translation Pop-up"

### ISSUE THREAD

**Issue by Fotispel** [you-apps/TranslateYou#453]
### Describe your suggested feature

When I select something for translation while, for example, I'm in the browser, and the pop-up with the translation appears, it will always be in English. It would be nice to be able to choose the language I want to translate it into.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
You actually can do this, just click the language name in row above the translation.
