### ISSUE TITLE
App Translation: Instant Translate On Screen

### ISSUE THREAD

**Issue by jujubeja** [you-apps/TranslateYou#455]
### Describe your suggested feature

App Translation: Instant Translate On Screen instantly translates text content in your app, whether it's a post/blog, chat conversation, or simple text, without the need to switch between translation software.

### Other details

Functional example You can try https://play.google.com/store/apps/details?id=com.spaceship.screen.textcopy

He can copy or translate the text in the image.
![Screenshot_20240925-093838](https://github.com/user-attachments/assets/a516f23b-bf8a-44af-b1b7-e84ba70aa5cd)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Sorry, that's not planned due to the difficulty and time needed of implementing such a feature.
