### ISSUE TITLE
Status bar / quick settings tile?

### ISSUE THREAD

**Issue by rafnov** [you-apps/TranslateYou#463]
### Describe your suggested feature

Would be nice to have quick access to translation via quick settings tile. Not all devices (like my Realme) support additional features like quick access sidebar visible on the screenshot. Besides it requires additional Internet permission, that I don't think is neccessary (spyware?), so I've removed it from system on one device and it remains not configured and not permitted to connect on another device.

![Screenshot_2024-10-29-06-45-54-85_9c7ad408470e52983cc8816adf9ff347](https://github.com/user-attachments/assets/238d5cfc-4e61-4972-8b14-dedc78be9860)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's not planned: You can already just long press any text in order to see the action menu which allows you to translate the text with Translate You.

**Comment by rafnov** [comment]
Thx, haven't noticed that feature.
