### ISSUE TITLE
Ability to select areas from images and apply filters while using the OCR

### ISSUE THREAD

**Issue by asereze** [you-apps/TranslateYou#465]
### Describe your suggested feature

When selecting an image to extract text from, it would be really useful to be able to see it inside the app and select a specific area of it. Right now, the entire image gets parsed, and that can create some issues when there are different blocks of text that could get erroneously mixed (for example, in a comic book page).
It would be even better to be able to apply some filters to the selected text before analysing it.

I don't know if it could be useful, but there are already some open source projects for Android that could be used as references:

**- Android OCR (OCR based on Tesseract 5)**
https://f-droid.org/packages/io.github.subhamtyagi.ocr/

https://github.com/SubhamTyagi/android-ocr

This one allows the user to import an image, rotate it and flip it before the analysis, and to apply some automatic pre-processing filters as well.

![Screenshot_20241029-223249_OCR](https://github.com/user-attachments/assets/a1fe6ca5-d9af-457c-a8e5-4f61d9816d26)
![Screenshot_20241029-223300_OCR](https://github.com/user-attachments/assets/022dc0f0-418e-49b2-af73-a80ac30afd01)
![Screenshot_20241029-223316_OCR](https://github.com/user-attachments/assets/acfc34cc-5a2e-4f24-b89d-d9cc6e4d778f)

**- Text Fairy**
https://apt.izzysoft.de/fdroid/index/apk/com.renard.ocr?repo=archive

https://github.com/renard314/textfairy

With this one you can select an area in a polygonal shape (especially useful for inclined photos, but not just that) and select multiple columns in the order that you prefer.

![Screenshot_20241029-223708_Text Fairy](https://github.com/user-attachments/assets/3ab3ac48-9428-4984-9ab1-f1f0bab9d162)
![Screenshot_20241029-223728_Text Fairy](https://github.com/user-attachments/assets/d3629f5c-4c5d-4fa8-8cf4-7c7671ac23c7)
![Screenshot_20241031-223015_Text Fairy](https://github.com/user-attachments/assets/a96d16ea-2938-4fa9-bb39-fea6e7c20a93)
![Screenshot_20241029-223747_Text Fairy](https://github.com/user-attachments/assets/36df4a5d-37fe-4f54-96ce-10bdf30ec17b)
![Screenshot_20241029-223843_Text Fairy](https://github.com/user-attachments/assets/47e021b6-b7dc-4374-89ec-0d70587064b6)

**- Kaku (Japanese OCR Dictionary)**
https://f-droid.org/packages/ca.fuwafuwa.kaku/

https://github.com/0xbad1d3a5/Kaku

Although this one works differently (it is displayed above the other apps), it allows you to select different areas one after the other and, by long tapping and dragging left or right, you can instantly change the contrast of the text within the selected area before parsing it. An automatic black and white filter for the same area is also available.

![Screenshot_20241031-224120_Firefox](https://github.com/user-attachments/assets/b129e79b-7a3e-4a67-88a7-29c03f3ff535)
![Screenshot_20241029-224620_Galleria](https://github.com/user-attachments/assets/2f6b6286-770d-4da5-846c-a05abbe6582f)
![Screenshot_20241029-224635_Galleria](https://github.com/user-attachments/assets/959a2c5d-3b60-4b29-a816-249dc9f89275)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by drogga** [comment]
Text Fairy's F-Droid link is invalid, it's not there, it's on PS tho, with inApps and Ads (the GH repo hasn't been updated since 4 years, up-to-date on Play Store).

**Comment by asereze** [comment]
@drogga I don't know why sharing it from the app doesn't work, the last FOSS version (4.1.0, the one that I used to make the screenshots) is available for download from the F-Droid Archive repository. Unfortunately yes, it's from 2021, the new releases' code is not available.

**Comment by drogga** [comment]
On your place, I would replace the not working f-droid.org link to it with: https://apt.izzysoft.de/fdroid/index/apk/com.renard.ocr?repo=archive, at least you don't have to have the app and be subscribed to the Archive repo.
Btw, I'm subscribed here, so you don't have ot mention me when you reply ;)

**Comment by asereze** [comment]
Ok, thank you!
