### ISSUE TITLE
pop-up when translating selected text

### ISSUE THREAD

**Issue by andsofine** [you-apps/TranslateYou#86]
### Describe your suggested feature

pop-up when translating selected text. instead of opening the app in full screen, as it happens so far

![Screenshot_20221117-002942](https://user-images.githubusercontent.com/99369164/202303322-3213aa4c-19ac-4122-965e-9d09c8934fa0.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Darkempire78** [comment]
I agree, it will be a very awesome improvement

**Comment by suhan-paradkar** [comment]
Yes.. since opening the app for selwcted text seems pretty much UX unfriendly...

**Comment by Bnyro** [comment]
No plans for that.

**Comment by natarslan** [comment]
👀

**Comment by ikanakova** [comment]
Does the reopening of this issue mean that this feature is in the plan again? Because only this feature will make this app a complete replacement of Google Translate for me.

**Comment by Bnyro** [comment]
It's planned, but there's no ETA.

**Comment by Bnyro** [comment]
https://github.com/you-apps/TranslateYou/pull/429
